### ISSUE TITLE
Update to 1.20.6 / 1.21

### ISSUE THREAD

**Issue by Kinqdos** [ByteExceptionM/laby-nbt-viewer#5]
Hey would you mind updating your awesome plugin to 1.20.6? I guess its just a config thing to enable it for 1.20.6
![image](https://github.com/ByteExceptionM/laby-nbt-viewer/assets/62080449/a5e1b89e-6754-4287-ac95-1a6b0e6b823c)

**Comment by SJ-Tom** [comment]
bump
it would be very useful because of the changes from microsoft to the new nbt components

**Comment by ByteExceptionM** [comment]
Gotcha

**Comment by SJ-Tom** [comment]
Jea now it would be cool if an update for 1.21 come in the near future

**Comment by ByteExceptionM** [comment]
1.21 support etc. is ready. Now waiting for release at FlintMC.
